### ISSUE TITLE
Handling of dates by parse_date() in the presence of empty strings

### ISSUE THREAD

**Issue by plogacev** [gaborcsardi/parsedate#10]
It appears that parse_date runs into problems when empty strings are present in the input vector. For example, the third date here is not recognized properly:

  > dates <-  c("", "2014-10-29", "2012-12-05")
  > parse_date(dates)
  [1] NA               "2014-10-29 UTC" "2014-10-29 UTC"

I am using parsedate_1.1.1 on R 3.2.0 (platform: x86_64-pc-linux-gnu, 64-bit) using Ubuntu 15.04.

**Comment by gaborcsardi** [comment]
Hmmm, the GitHub version does not seem to have this issue.

**Comment by plogacev** [comment]
I just reinstalled from github and can confirm that the issue does not seem to occur anymore.

**Comment by gaborcsardi** [comment]
OK. Thanks! I'll submit a release to CRAN soon.

**Comment by plogacev** [comment]
Thank you for the package! :)
