### ISSUE TITLE
parse_date(character(0)) gives error

### ISSUE THREAD

**Issue by wch** [gaborcsardi/parsedate#20]
```R
parse_date(character(0))
#> Error during wrapup: parse_date argument must be character
```

The problem is due to `sapply`: if the input is `character(0)`, it returns `list()`:
https://github.com/gaborcsardi/parsedate/blob/a7f4b1e25a8d95778119c48fa39fd489424f2bd0/R/parsedate-package.r#L90

Just another reason to not use `sapply`. :)

**Comment by gaborcsardi** [comment]
Yeah. I was young and careless.

**Comment by gaborcsardi** [comment]
Oh, wait, it wasn't me, actually. :)

**Comment by wch** [comment]
But I do see that you used `sapply` elsewhere, so you're not totally innocent.

While you're in there, this line uses partial argument matching for the `length.out` argument:

https://github.com/gaborcsardi/parsedate/blob/a7f4b1e25a8d95778119c48fa39fd489424f2bd0/R/parsedate-package.r#L88

```R
rep(as.POSIXct(NA), length = length(dates))
```
