### ISSUE TITLE
parse_iso_8601 extremely slow

### ISSUE THREAD

**Issue by veita** [gaborcsardi/parsedate#9]
Given a data frame with two columns and 4 million rows. Each row in the first column contains a date string of the form 2015-05-12T12:30:59.

The R command df$col1 <- parse_iso_8601(df$col1) takes seemingly endless time (had to cancel the operation after 40 minutes).

Under normal circumstances such a parsing operation is expected o take less than 5 seconds.

Hardware: Intel Xeon 16 cores, 32 GB RAM

**Comment by gaborcsardi** [comment]
Yes it is bad. I will need to rewrite most things in C/C++, because it is not a single function that is slow, but many together.

**Comment by gaborcsardi** [comment]
Maybe some vectorization could actually solve this....
